wgpu_context: Fix `Timeout` crash in when getting surface texture (#38)
Using `AnyRender` from Blitz crashes on my machine when trying to
present the first frame, running Blitz on commit
`bdbe4d3f2a1d8bd3e7b77cd163bb4de280738550` with the following command:

```
cargo run -rp browser --no-default-features --features floats,incremental,cookies,cache,log_frame_times,hybrid
```

I believe the issue is because `wgpu_context::SurfaceRenderer` calls and
discards the result of `wgpu::Surface::get_current_texture` multiple
times, which my not be handled gracefully on all hardware. It crashes on
both my AMD cards (one dedicated GPU of a desktop, one AMD Radeon 860M).

[Dropping a `wgpu::SurfaceTexture`](https://docs.rs/wgpu/28.0.0/src/wgpu/api/surface_texture.rs.html#49-53)
without having presented it actually goes into a discard code path,
ending up here:
https://github.com/gfx-rs/wgpu/blob/2c9e77a19d051d06950d9feaddb3463967a32827/wgpu-core/src/present.rs#L409-L420.
I believe the intention is that once the surface texture was acquired,
it should be
[`SurfaceTexture::present`ed](https://docs.rs/wgpu/28.0.0/wgpu/struct.SurfaceTexture.html#method.present).

This PR makes `SurfaceRenderer` a bit more heavy-handed, requiring
mutable access, but has the upside of hiding the surface texture
handling. A more targeted patch fixing the crash (but not really the
underlying issue) is as follows.

```patch
index 0d2f973..c94f816 100644
--- a/crates/anyrender_vello/src/window_renderer.rs
+++ b/crates/anyrender_vello/src/window_renderer.rs
@@ -224,7 +224,7 @@ impl WindowRenderer for VelloWindowRenderer {
             .expect("failed to render to texture");
         timer.record_time("render");

-        render_surface.maybe_blit_and_present();
+        render_surface.maybe_blit_and_present(render_surface.current_surface_texture());
         timer.record_time("present");

         render_surface
diff --git a/crates/anyrender_vello_hybrid/src/window_renderer.rs b/crates/anyrender_vello_hybrid/src/window_renderer.rs
index 28958af..2c23c8c 100644
--- a/crates/anyrender_vello_hybrid/src/window_renderer.rs
+++ b/crates/anyrender_vello_hybrid/src/window_renderer.rs
@@ -243,9 +243,7 @@ impl WindowRenderer for VelloHybridWindowRenderer {
         timer.record_time("render");

         drop(texture_view);
-        drop(surface_texture);
-
-        render_surface.maybe_blit_and_present();
+        render_surface.maybe_blit_and_present(surface_texture);
         timer.record_time("present");

         render_surface
diff --git a/crates/wgpu_context/src/surface_renderer.rs b/crates/wgpu_context/src/surface_renderer.rs
index 4fb46a6..65182ee 100644
--- a/crates/wgpu_context/src/surface_renderer.rs
+++ b/crates/wgpu_context/src/surface_renderer.rs
@@ -208,12 +208,7 @@ impl<'s> SurfaceRenderer<'s> {
         }
     }

-    pub fn maybe_blit_and_present(&self) {
-        let surface_texture = self
-            .surface
-            .get_current_texture()
-            .expect("failed to get surface texture");
-
+    pub fn maybe_blit_and_present(&self, surface_texture: SurfaceTexture) {
         if let Some(its) = &self.intermediate_texture {
             self.blit_from_intermediate_texture_to_surface(&surface_texture, its);
         }
```

Backtrace:

```
thread 'main' (126269) panicked at /home/thomas/code/linebender/anyrender/crates/wgpu_context/src/surface_renderer.rs:215:14:
failed to get surface texture: Timeout
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <wgpu_context::surface_renderer::SurfaceRenderer>::maybe_blit_and_present
   4: <anyrender_vello_hybrid::window_renderer::VelloHybridWindowRenderer as anyrender::WindowRenderer>::render::<<blitz_shell::window::View<dioxus_native::dioxus_renderer::DioxusNativeWindowRenderer>>::redraw::{closure#0}>
   5: <blitz_shell::window::View<dioxus_native::dioxus_renderer::DioxusNativeWindowRenderer>>::handle_winit_event
   6: <blitz_shell::application::BlitzApplication<dioxus_native::dioxus_renderer::DioxusNativeWindowRenderer> as winit::application::ApplicationHandler<blitz_shell::event::BlitzShellEvent>>::window_event
   7: <&mut <winit::event_loop::EventLoop<blitz_shell::event::BlitzShellEvent>>::run_app<dioxus_native::dioxus_application::DioxusNativeApplication>::{closure#0} as core::ops::function::FnMut<(winit::event::Event<blitz_shell::event::BlitzShellEvent>, &winit::event_loop::ActiveEventLoop)>>::call_mut
   8: <winit::platform_impl::linux::wayland::event_loop::EventLoop<blitz_shell::event::BlitzShellEvent>>::pump_events::<&mut <winit::event_loop::EventLoop<blitz_shell::event::BlitzShellEvent>>::run_app<dioxus_native::dioxus_application::DioxusNativeApplication>::{closure#0}>
   9: <winit::platform_impl::linux::wayland::event_loop::EventLoop<blitz_shell::event::BlitzShellEvent>>::run_on_demand::<<winit::event_loop::EventLoop<blitz_shell::event::BlitzShellEvent>>::run_app<dioxus_native::dioxus_application::DioxusNativeApplication>::{closure#0}>
  10: dioxus_native::launch_cfg
  11: dioxus_native::launch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```